My portfolio setup
Eugeneiyukhun/My_Portfolio_Setup pull request #1
Opened 2022-10-27 08:41 UTC by Eugeneiyukhun

2022-10-27 10:24 UTC, MaganaAsiati requested changes
# STATUS: Required Changes ♻️♻️♻️ 

Hi @Eugeneiyukhun 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![AlonzoLeroneThisCloseGIF](https://user-images.githubusercontent.com/50941074/161814298-b87179c3-315f-4207-ac3b-1d3e584d506e.gif)

## Highlights
✅ No linter error
✅ README is professional
✅ correct [GitHub Flow](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/git-github/articles/github_flow.md):

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2022-10-27 10:24 UTC, MaganaAsiati commented on index.html
> +    </header>
- You did a great job by aligning correctly your hamburger menu and your logo but kindly make sure the core you use this color  `color: #6070FF;` provide in the Figma design and reduce a bit the font size 'font-size: 1.5em;' of your hamburger so 
that it will make your header section design stick to the Figma design as it was required in the project. :+1:  :sunglasses: 

## Your design 
![image](https://user-images.githubusercontent.com/95297251/198253236-c8bfd7f1-7e5b-4e51-a852-73bd91ed99ae.png)


## Figma design 

![image](https://user-images.githubusercontent.com/95297251/198253129-a4610909-9a89-49ae-95a7-57d269045e79.png)

2022-10-27 10:24 UTC, MaganaAsiati commented on index.html
> +                </div>
- Kindly make sure 'LET' S CONNECT' look exactly like it shows in the Figma design,  try to adjust a bit the font size and the color ' color: #7F8CFF; ' so that it will make your design look like the Figma design :+1: 
- Kindly make sure that your social icons design sticks as much as possible to the Figma design as shown in the picture below your icons are not correctly visible, and the color and the font size are not the same kindly make sure you fix that If it's pretty and works, it will be a wonderful website :+1: 

## Figma design 

![image](https://user-images.githubusercontent.com/95297251/198255124-4703c17e-82ca-44ed-a1e8-46b67df2f07a.png)

## your design 

![image](https://user-images.githubusercontent.com/95297251/198259646-6662c9ad-636e-4e23-b5ea-2372490e2d2c.png)

2022-10-27 19:59 UTC, codecaiine commented on index.html
> +    </header>
- [ ] [REQUIRED] Good job so far by improving your menu but as mentioned by the previous reviewer, please make sure that your hamburger menu has the same color defined on the Figma template as a developer it is very important to pay attention to details :smile:  Check the screenshots below to see the differences :arrow_down: 

![Screenshot from 2022-10-27 19-52-18](https://user-images.githubusercontent.com/6615394/198386511-e39e61d4-aeb4-4b5e-88f8-768d197e3a4c.png)
![Screenshot from 2022-10-27 19-52-05](https://user-images.githubusercontent.com/6615394/198386514-ea2ef931-fb10-4d4e-9517-bfddf913ca86.png)
![Screenshot from 2022-10-27 19-51-51](https://user-images.githubusercontent.com/6615394/198386516-add40436-c36d-4475-8081-4e34c4df8b99.png)
![Screenshot from 2022-10-27 19-47-08-social](https://user-images.githubusercontent.com/6615394/198386521-5b700590-a612-4345-b0e5-b4f0bccc524d.jpg)
![Screenshot from 2022-10-27 19-47-08-menu](https://user-images.githubusercontent.com/6615394/198386525-3587f7c8-6b40-4ca8-9fa6-4c1004a358f8.jpg)

2022-10-27 20:12 UTC, codecaiine commented on index.html
> +                </div>
- [ ] [REQUIRED] Good job so far :clap: But I noticed a few differences between this section design and the Figma template :cry: As the previous reviewer mentioned it is very important that you stick to the Figma design as much as possible. Please improve this part in order to have the expected design :smile: 

### Your design
![Screenshot from 2022-10-27 19-52-18](https://user-images.githubusercontent.com/6615394/198386511-e39e61d4-aeb4-4b5e-88f8-768d197e3a4c.png)

### Figma design

![Screenshot from 2022-10-27 19-47-08-social](https://user-images.githubusercontent.com/6615394/198386521-5b700590-a612-4345-b0e5-b4f0bccc524d.jpg)

2022-10-27 20:14 UTC, codecaiine requested changes
Hi @Eugeneiyukhun , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights
- Great UI design :heavy_check_mark: 
- No linters errors :heavy_check_mark: 
- Good project implementation :heavy_check_mark: 

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me (@codecaiine) in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-27 21:35 UTC, Eugeneiyukhun commented
I don't know the names of those social link icons.
I need help.
I have been on my sit for almost 24hrs.
I need help

On Thu, Oct 27, 2022, 11:24 AM Assiati Magana ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
> STATUS: Required Changes ♻️♻️♻️
>
> Hi @Eugeneiyukhun <https://github.com/Eugeneiyukhun>
>
> Good job so far!
> There are some issues that you still need to work on to go to the next
> project but you are almost there!
>
> [image: AlonzoLeroneThisCloseGIF]
> <https://user-images.githubusercontent.com/50941074/161814298-b87179c3-315f-4207-ac3b-1d3e584d506e.gif>
> Highlights
>
> ✅ No linter error
> ✅ README is professional
> ✅ correct GitHub Flow
> <https://github.com/microverseinc/curriculum-transversal-skills/blob/main/git-github/articles/github_flow.md>
> :
> Required Changes ♻️
>
> *Check the comments under the review.*
> Optional suggestions
>
> *Every comment with the [OPTIONAL] prefix is not crucial enough to stop
> the approval of this PR. However, I strongly recommend you to take them
> into account as they can make your code better.*
>
> Cheers and Happy coding!👏👏👏
>
> Feel free to leave any questions or comments in the PR thread if something
> is not 100% clear.
> Please, remember to tag me in your question so I can receive the
> notification.
>
> *Please, do not open a new Pull Request for re-reviews. You should use the
> same Pull Request submitted for the first review, either valid or invalid
> unless it is requested otherwise.*
> ------------------------------
>
> *As described in the Code reviews limits policy
> <https://microverse.zendesk.com/hc/en-us/articles/1500004088561> you have a
> limited number of reviews per project (check the exact number in your
> Dashboard). If you think that the code review was not fair, you can request
> a second opinion using this form <https://airtable.com/shrQAqnBwek5a0O0s>.*
>
> ------------------------------
>
> In index.html
> <https://github.com/Eugeneiyukhun/My_Portfolio_Setup/pull/1#discussion_r1006647773>
> :
>
> > +    <header class="header">
>
> +        <div class="header-container">
>
> +            <a href="#" class="logo">My Logo</a>
>
> +            <nav class="nav">
>
> +                <i class="fa fa-bars fa-2x"></i>
>
> +            </nav>
>
> +        </div>
>
> +    </header>
>
>
>
>    - You did a great job by aligning correctly your hamburger menu and
>    your logo but kindly make sure the core you use this color color:
>    #6070FF; provide in the Figma design and reduce a bit the font size
>    'font-size: 1.5em;' of your hamburger so
>    that it will make your header section design stick to the Figma design
>    as it was required in the project. 👍 😎
>
> Your design
>
> [image: image]
> <https://user-images.githubusercontent.com/95297251/198253236-c8bfd7f1-7e5b-4e51-a852-73bd91ed99ae.png>
> Figma design
>
> [image: image]
> <https://user-images.githubusercontent.com/95297251/198253129-a4610909-9a89-49ae-95a7-57d269045e79.png>
> ------------------------------
>
> In index.html
> <https://github.com/Eugeneiyukhun/My_Portfolio_Setup/pull/1#discussion_r1006686495>
> :
>
> > +                <div class="social-links">
>
> +                    <h2>LETS CONNECT</h2>
>
> +                    <ul>
>
> +                        <li><a href="#"><i class="fa fa-facebook fa-2x"></i></a></li>
>
> +                        <li><a href="#"><i class="fa fa-twitter fa-2x"></i></a></li>
>
> +                        <li><a href="#"><i class="fa fa-github fa-2x"></i></a></li>
>
> +                        <li><a href="#"><i class="fa fa-instagram fa-2x"></i></a></li>
>
> +                        <li><a href="#"><i class="fa fa-linkedin fa-2x"></i></a></li>
>
> +                    </ul>
>
> +
>
> +                </div>
>
>
>
>    - Kindly make sure 'LET' S CONNECT' look exactly like it shows in the
>    Figma design, try to adjust a bit the font size and the color ' color:
>    #7F8CFF; ' so that it will make your design look like the Figma design
>    👍
>    - Kindly make sure that your social icons design sticks as much as
>    possible to the Figma design as shown in the picture below your icons are
>    not correctly visible, and the color and the font size are not the same
>    kindly make sure you fix that If it's pretty and works, it will be a
>    wonderful website 👍
>
> Figma design
>
> [image: image]
> <https://user-images.githubusercontent.com/95297251/198255124-4703c17e-82ca-44ed-a1e8-46b67df2f07a.png>
> your design
>
> [image: image]
> <https://user-images.githubusercontent.com/95297251/198259646-6662c9ad-636e-4e23-b5ea-2372490e2d2c.png>
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Eugeneiyukhun/My_Portfolio_Setup/pull/1#pullrequestreview-1157954205>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AZOZO63USYKQLSOEEEL6GHDWFJJ6XANCNFSM6AAAAAARPZXPKA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-10-28 07:47 UTC, Eugeneiyukhun commented
Yes!
I have resolved it.
Though it took me the whole night to get it.
Thank you so much, reviewers.
This has made me learn much.

On Thu, Oct 27, 2022, 10:35 PM Eugene Iyukhun ***@***.***>
wrote:

> I don't know the names of those social link icons.
> I need help.
> I have been on my sit for almost 24hrs.
> I need help
>
> On Thu, Oct 27, 2022, 11:24 AM Assiati Magana ***@***.***>
> wrote:
>
>> ***@***.**** requested changes on this pull request.
>> STATUS: Required Changes ♻️♻️♻️
>>
>> Hi @Eugeneiyukhun <https://github.com/Eugeneiyukhun>
>>
>> Good job so far!
>> There are some issues that you still need to work on to go to the next
>> project but you are almost there!
>>
>> [image: AlonzoLeroneThisCloseGIF]
>> <https://user-images.githubusercontent.com/50941074/161814298-b87179c3-315f-4207-ac3b-1d3e584d506e.gif>
>> Highlights
>>
>> ✅ No linter error
>> ✅ README is professional
>> ✅ correct GitHub Flow
>> <https://github.com/microverseinc/curriculum-transversal-skills/blob/main/git-github/articles/github_flow.md>
>> :
>> Required Changes ♻️
>>
>> *Check the comments under the review.*
>> Optional suggestions
>>
>> *Every comment with the [OPTIONAL] prefix is not crucial enough to stop
>> the approval of this PR. However, I strongly recommend you to take them
>> into account as they can make your code better.*
>>
>> Cheers and Happy coding!👏👏👏
>>
>> Feel free to leave any questions or comments in the PR thread if
>> something is not 100% clear.
>> Please, remember to tag me in your question so I can receive the
>> notification.
>>
>> *Please, do not open a new Pull Request for re-reviews. You should use
>> the same Pull Request submitted for the first review, either valid or
>> invalid unless it is requested otherwise.*
>> ------------------------------
>>
>> *As described in the Code reviews limits policy
>> <https://microverse.zendesk.com/hc/en-us/articles/1500004088561> you have a
>> limited number of reviews per project (check the exact number in your
>> Dashboard). If you think that the code review was not fair, you can request
>> a second opinion using this form <https://airtable.com/shrQAqnBwek5a0O0s>.*
>>
>> ------------------------------
>>
>> In index.html
>> <https://github.com/Eugeneiyukhun/My_Portfolio_Setup/pull/1#discussion_r1006647773>
>> :
>>
>> > +    <header class="header">
>>
>> +        <div class="header-container">
>>
>> +            <a href="#" class="logo">My Logo</a>
>>
>> +            <nav class="nav">
>>
>> +                <i class="fa fa-bars fa-2x"></i>
>>
>> +            </nav>
>>
>> +        </div>
>>
>> +    </header>
>>
>>
>>
>>    - You did a great job by aligning correctly your hamburger menu and
>>    your logo but kindly make sure the core you use this color color:
>>    #6070FF; provide in the Figma design and reduce a bit the font size
>>    'font-size: 1.5em;' of your hamburger so
>>    that it will make your header section design stick to the Figma
>>    design as it was required in the project. 👍 😎
>>
>> Your design
>>
>> [image: image]
>> <https://user-images.githubusercontent.com/95297251/198253236-c8bfd7f1-7e5b-4e51-a852-73bd91ed99ae.png>
>> Figma design
>>
>> [image: image]
>> <https://user-images.githubusercontent.com/95297251/198253129-a4610909-9a89-49ae-95a7-57d269045e79.png>
>> ------------------------------
>>
>> In index.html
>> <https://github.com/Eugeneiyukhun/My_Portfolio_Setup/pull/1#discussion_r1006686495>
>> :
>>
>> > +                <div class="social-links">
>>
>> +                    <h2>LETS CONNECT</h2>
>>
>> +                    <ul>
>>
>> +                        <li><a href="#"><i class="fa fa-facebook fa-2x"></i></a></li>
>>
>> +                        <li><a href="#"><i class="fa fa-twitter fa-2x"></i></a></li>
>>
>> +                        <li><a href="#"><i class="fa fa-github fa-2x"></i></a></li>
>>
>> +                        <li><a href="#"><i class="fa fa-instagram fa-2x"></i></a></li>
>>
>> +                        <li><a href="#"><i class="fa fa-linkedin fa-2x"></i></a></li>
>>
>> +                    </ul>
>>
>> +
>>
>> +                </div>
>>
>>
>>
>>    - Kindly make sure 'LET' S CONNECT' look exactly like it shows in the
>>    Figma design, try to adjust a bit the font size and the color ' color:
>>    #7F8CFF; ' so that it will make your design look like the Figma design
>>    👍
>>    - Kindly make sure that your social icons design sticks as much as
>>    possible to the Figma design as shown in the picture below your icons are
>>    not correctly visible, and the color and the font size are not the same
>>    kindly make sure you fix that If it's pretty and works, it will be a
>>    wonderful website 👍
>>
>> Figma design
>>
>> [image: image]
>> <https://user-images.githubusercontent.com/95297251/198255124-4703c17e-82ca-44ed-a1e8-46b67df2f07a.png>
>> your design
>>
>> [image: image]
>> <https://user-images.githubusercontent.com/95297251/198259646-6662c9ad-636e-4e23-b5ea-2372490e2d2c.png>
>>
>> —
>> Reply to this email directly, view it on GitHub
>> <https://github.com/Eugeneiyukhun/My_Portfolio_Setup/pull/1#pullrequestreview-1157954205>,
>> or unsubscribe
>> <https://github.com/notifications/unsubscribe-auth/AZOZO63USYKQLSOEEEL6GHDWFJJ6XANCNFSM6AAAAAARPZXPKA>
>> .
>> You are receiving this because you were mentioned.Message ID:
>> ***@***.***>
>>
>

2022-10-28 08:06 UTC, levy002 requested changes
## Hello @Eugeneiyukhun   , :wave:
### I'm Levy, your PR reviewer

Good job so far :+1: 
There are some issues that you still need to work on to go to the next project but you are almost there!

![](https://media.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif)

## Status: REQUIRED CHANGES ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @levy002 in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-28 08:06 UTC, levy002 commented on styles.css
> +}
- [ ] Kindly align your background image correctly in order with the provided Figma design. :wink: 
    **_Hint:_** Add this  `background-size: cover` and see how it affects your design.

    - ### Your design
     ![image](https://user-images.githubusercontent.com/87197412/198536426-5390900f-7ba8-48d5-ae1e-a8dcacc80ad1.png)

   - ### Figma design
    ![image](https://user-images.githubusercontent.com/87197412/198536578-37f8ffe2-7568-4302-a120-ee958e2635da.png)

2022-10-28 08:37 UTC, levy002 approved these changes
### Hello @Eugeneiyukhun 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![](https://media.giphy.com/media/jJQC2puVZpTMO4vUs0/giphy.gif)

## Status: APPROVED :fire:  :fire: 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-28 08:48 UTC, merged