I modified readme.md, index.html,styles.css, I also added images.
Eugeneiyukhun/My_Portfolio_Setup pull request #2
Opened 2022-10-28 13:11 UTC by Eugeneiyukhun

I built a portfolio with mobile and desktop views using
- Linter
- HTML and CSS
- flex.

2022-10-28 13:27 UTC, leonardodiasb requested changes
# Required Changes ♻️ ⚠️ 🚦 

Hi @Eugeneiyukhun, 

Good job so far!
You still need to work on some issues to go to the next project, but you are almost there!

![mario_ladders](https://user-images.githubusercontent.com/20563252/121369265-4e418880-c901-11eb-848c-1eff06d5a4cf.gif)

## Good points 👍 

 - No linter errors. ✔️
 - Correct use of Github flow. ✔️ 

## Aspects to improve ♻️

- [x] Check the comments under the review.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-28 13:27 UTC, leonardodiasb commented on index.html
> +                <h1>About Myself</h1>
- [ ] This is the title of this section, but not the title of the page. Usually, the page has one main title and no more than one `h1` tag. Please change this to a `h2` and read [this article](https://www.reliablesoft.net/h1-tag/) for a better understanding of the headings and SEO.

2022-10-28 13:27 UTC, leonardodiasb commented on styles.css
> +}
- [ ] This section is great and very similar to the Figma template, but it is a project requirement to style it with Flexbox. Please, add flexbox to this class to follow all the instructions.

2022-10-29 06:41 UTC, aimalamiri requested changes
Hi @Eugeneiyukhun, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![AlmostThereReachGIF](https://user-images.githubusercontent.com/34779928/191356050-93e2eb80-7c05-4749-92f7-8925a1fa9386.gif)


 ## Highlights

- The mobile version is designed very well and looks fantastic ✔️ ⭐
- Good job for using the right GitHub Flow 💯
- Awesome file organization 🗃️
- Commits are descriptive and meaningful 👍
- Linters are properly set up and passing 🟢 👍

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-29 06:41 UTC, aimalamiri commented on index.html
> +                            <span>Languages</span>
It looks amazing 👌but you can improve it by following the exact Figma design. Please make sure to fix the font-weight here. These kinds of simple things can improve your design significantly.

![image](https://user-images.githubusercontent.com/34779928/198817838-ac39db1f-2743-446f-9e2a-e2b12ef3f03f.png)

2022-10-29 10:06 UTC, Felix45 approved these changes
# Approved :green_circle: 
Hi @Eugeneiyukhun , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights :heavy_check_mark: 
- [ ] Nice UI design :white_check_mark: 
- [ ] Linters are set up correctly and passing :white_check_mark: 
- [ ] Good descriptive commit messages :white_check_mark: 
- [ ] Descriptive pull request and summary :white_check_mark: 

![](https://user-images.githubusercontent.com/65852621/133696182-6c5b784b-0083-427a-b24d-3ec870915f79.jpg)

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-29 15:31 UTC, merged